export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_DETAIL_REQUEST = 'SIGNUP_DETAIL_REQUEST';
export const SIGNUP_DETAIL_SUCCESS = 'SIGNUP_DETAIL_SUCCESS';
export const SIGNUP_DETAIL_FAIL = 'SIGNUP_DETAIL_FAIL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const GET_ADMIN_GOALS_REQUEST = 'GET_ADMIN_GOALS_REQUEST';
export const GET_ADMIN_GOALS_SUCCESS = 'GET_ADMIN_GOALS_SUCCESS';
export const GET_ADMIN_GOALS_FAIL = 'GET_ADMIN_GOALS_FAIL';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';

export const ADD_REFLECTIONS_REQUEST = 'ADD_REFLECTIONS_REQUEST';
export const ADD_REFLECTIONS_SUCCESS = 'ADD_REFLECTIONS_SUCCESS';
export const ADD_REFLECTIONS_FAIL = 'ADD_REFLECTIONS_FAIL';

export const GET_REFLECTIONS_REQUEST = 'GET_REFLECTIONS_REQUEST';
export const GET_REFLECTIONS_SUCCESS = 'GET_REFLECTIONS_SUCCESS';
export const GET_REFLECTIONS_FAIL = 'GET_REFLECTIONS_FAIL';

export const SAVE_GRATEFUL_LIST_REQUEST = 'SAVE_GRATEFUL_LIST_REQUEST';
export const SAVE_GRATEFUL_LIST_SUCCESS = 'SAVE_GRATEFUL_LIST_SUCCESS';
export const SAVE_GRATEFUL_LIST_FAIL = 'SAVE_GRATEFUL_LIST_FAIL';
export const SET_CURRENT_STRIKE_REQUEST = 'SET_CURRENT_STRIKE_REQUEST';
export const SET_CURRENT_STRIKE_SUCCESS = 'SET_CURRENT_STRIKE_SUCCESS';
export const SET_CURRENT_STRIKE_FAIL = 'SET_CURRENT_STRIKE_FAIL';

export const SET_TASK_COMPLETED_REQUEST = 'SET_TASK_COMPLETED_REQUEST';
export const SET_TASK_COMPLETED_SUCCESS = 'SET_TASK_COMPLETED_SUCCESS';
export const SET_TASK_COMPLETED_FAIL = 'SET_TASK_COMPLETED_FAIL';

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = ' CREATE_TASK_FAIL';

export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAIL = ' CREATE_PROFILE_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_LOGS_REQUEST = 'GET_LOGS_REQUEST';
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS';
export const GET_LOGS_FAIL = ' GET_LOGS_FAIL';

export const GET_TODAYS_REFLECTION_REQUEST = 'GET_TODAYS_REFLECTION_REQUEST';
export const GET_TODAYS_REFLECTION_SUCCESS = 'GET_TODAYS_REFLECTION_SUCCESS';
export const GET_TODAYS_REFLECTION_FAIL = 'GET_TODAYS_REFLECTION_FAIL';

export const GET_SOBER_DATES_REQUEST = 'GET_SOBER_DATES_REQUEST';
export const GET_SOBER_DATES_SUCCESS = 'GET_SOBER_DATES_SUCCESS';
export const GET_SOBER_DATES_FAIL = 'GET_SOBER_DATES_FAIL';

export const SET_MOOD_REQUEST = 'SET_MOOD_REQUEST';
export const SET_MOOD_SUCCESS = 'SET_MOOD_SUCCESS';
export const SET_MOOD_FAIL = 'SET_MOOD_FAIL';

export const CREATE_MILESTONE_REQUEST = 'CREATE_MILESTONE_REQUEST';
export const CREATE_MILESTONE_SUCCESS = 'CREATE_MILESTONE_SUCCESS';
export const CREATE_MILESTONE_FAIL = 'CREATE_MILESTONE_FAIL';

export const DELETE_MILESTONE_REQUEST = 'DELETE_MILESTONE_REQUEST';
export const DELETE_MILESTONE_SUCCESS = 'DELETE_MILESTONE_SUCCESS';
export const DELETE_MILESTONE_FAIL = 'DELETE_MILESTONE_FAIL';

export const GET_ALL_GROUPS_REQUEST = 'GET_ALL_GROUPS_REQUEST';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const GET_ALL_GROUPS_FAIL = 'GET_ALL_GROUPS_FAIL';

export const GET_GRATITUDE_LIST_REQUEST = 'GET_GRATITUDE_LIST_REQUEST';
export const GET_GRATITUDE_LIST_SUCCESS = 'GET_GRATITUDE_LIST_SUCCESS';
export const GET_GRATITUDE_LIST_FAIL = 'GET_GRATITUDE_LIST_FAIL';

export const GET_GROUP_DETAIL_REQUEST = 'GET_GROUP_DETAIL_REQUEST';
export const GET_GROUP_DETAIL_SUCCESS = 'GET_GROUP_DETAIL_SUCCESS';
export const GET_GROUP_DETAIL_FAIL = 'GET_GROUP_DETAIL_FAIL';

export const GET_GROUP_POSTS_REQUEST = 'GET_GROUP_POSTS_REQUEST';
export const GET_GROUP_POSTS_SUCCESS = 'GET_GROUP_POSTS_SUCCESS';
export const GET_GROUP_POSTS_FAIL = 'GET_GROUP_POSTS_FAIL';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_ALL_ACTIVITIES_REQUEST = 'GET_ALL_ACTIVITIES_REQUEST';
export const GET_ALL_ACTIVITIES_SUCCESS = 'GET_ALL_ACTIVITIES_SUCCESS';
export const GET_ALL_ACTIVITIES_FAIL = 'GET_ALL_ACTIVITIES_FAIL';

export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAIL = 'LEAVE_GROUP_FAIL';

export const JOIN_GROUP_REQUEST = 'JOIN_GROUP_REQUEST';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_FAIL = 'JOIN_GROUP_FAIL';

export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';
